#!/bin/sh
# Groundwork quickstart — generated-credentials entrypoint.
#
# Wraps `docker compose -f infra/docker-compose.quickstart.yml up -d` so the
# demo bootstrap API key and audit salt are random per-machine instead of the
# repo-published defaults. Both values are written to infra/.env.quickstart
# (gitignored) and printed once, so the same command works on later runs.
#
# The compose file still ships safe local/demo defaults when run directly:
#   docker compose -f infra/docker-compose.quickstart.yml up -d
# Use this script when you want the demo stack to exercise the real
# generated-credential path.
set -eu

COMPOSE_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$COMPOSE_DIR/.env.quickstart"

if [ ! -f "$ENV_FILE" ]; then
  umask 077
  {
    echo "# Generated by infra/scripts/quickstart.sh — do not commit (gitignored)."
    echo "BOOTSTRAP_API_KEY=gw_live_$(od -An -N8 -tx1 /dev/urandom | tr -d ' \n')_$(od -An -N48 -tx1 /dev/urandom | tr -d ' \n')"
    echo "IMMUTABLE_AUDIT_SALT=$(od -An -N32 -tx1 /dev/urandom | tr -d ' \n')"
  } > "$ENV_FILE"
  echo "[quickstart] generated $ENV_FILE"
else
  echo "[quickstart] reusing existing $ENV_FILE"
fi

docker compose --env-file "$ENV_FILE" -f "$COMPOSE_DIR/docker-compose.quickstart.yml" up -d
echo "[quickstart] stack starting. Console: http://localhost:3000  Runtime: http://localhost:8080"
echo "[quickstart] bootstrap API key (also in $ENV_FILE):"
grep '^BOOTSTRAP_API_KEY=' "$ENV_FILE"
