// init scaffolds a sovereign deployment directory: groundwork.env with
// generated key material, an RSA delegation key pair, a validated
// starter policy, and a short README. Idempotent: existing files are
// left untouched unless --force is given.
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/hex"
	"encoding/pem"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

const envTemplate = `# groundwork.env — generated by ` + "`groundwork init`" + ` (do not commit secrets)
# GROUNDWORK_ENV=production enables the fail-closed production checks in
# deployment.Validate (required keys, audit storage, no demo identity).
GROUNDWORK_ENV=local
# Set to the deployment region (uk|eu|us) to activate sovereign
# deployment validation at runtime startup.
# GROUNDWORK_TENANT_REGIONS=uk:uk,eu:eu
# GROUNDWORK_DEPLOYMENT_REGION=uk
# GROUNDWORK_JURISDICTION=GB

# --- Identity ---------------------------------------------------------
# Enterprise OIDC (preferred over the JWT secret in production):
# GROUNDWORK_OIDC_ISSUER=https://id.example.com/
# GROUNDWORK_OIDC_CLIENT_ID=groundwork
# GROUNDWORK_JWT_HS_SECRET is also used by the console proxy to mint
# short-lived console-admin JWTs — set it (>= 32 chars, high entropy).
GROUNDWORK_JWT_HS_SECRET=%[1]s

# --- Delegation signing (RS256 preferred) ----------------------------
# A generated key pair is written to delegation-rs256.pem(.pub) and
# wired via the FILE variable. Alternatively set
# GROUNDWORK_DELEGATION_RS_PRIVATE_KEY (inline PEM) or
# GROUNDWORK_DELEGATION_HS_SECRET (>= 32 chars).
GROUNDWORK_DELEGATION_RS_PRIVATE_KEY_FILE=%[2]s
GROUNDWORK_DELEGATION_HS_SECRET=%[3]s

# --- Outbox webhook (Phase 3 delivery) --------------------------------
# Set to the destination URL and the generated secret to enable
# transactional outbox delivery of governance/registry lifecycle events.
# GROUNDWORK_OUTBOX_WEBHOOK_URL=https://hooks.example.com/groundwork
GROUNDWORK_OUTBOX_WEBHOOK_SECRET=%[4]s

# --- Core services ------------------------------------------------------
DATABASE_URL=postgres://groundwork:groundwork@localhost:5432/groundwork?sslmode=disable
# SpiceDB: preshared key from the spicedb container (see infra/docker-compose.yml).
SPICEDB_ENDPOINT=localhost:50051
SPICEDB_TOKEN=groundwork-local
SPICEDB_INSECURE_PLAINTEXT=true
QDRANT_URL=http://localhost:6333
ELASTICSEARCH_URL=http://localhost:9200

# --- Demo identity: never true in production ---------------------------
ALLOW_DEMO_IDENTITY=false
# Observe-only mode: evaluate and log what WOULD be blocked without
# stripping. Safe to enable during onboarding.
# GROUNDWORK_SHADOW_MODE=true
`

type initOptions struct {
	dir      string
	template string
	force    bool
}

func runInit(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dir := fs.String("dir", ".groundwork", "directory to scaffold into")
	template := fs.String("template", "read-only-research", "starter policy template name")
	force := fs.Bool("force", false, "overwrite existing files")
	if err := fs.Parse(args); err != nil {
		return exitUsage
	}
	if fs.NArg() > 0 {
		fmt.Fprintf(stderr, "init: unexpected argument %q\n", fs.Arg(0))
		return exitUsage
	}

	opts := initOptions{dir: *dir, template: *template, force: *force}
	if err := scaffold(opts, stdout); err != nil {
		fmt.Fprintf(stderr, "init: %v\n", err)
		return exitCheck
	}
	return exitOK
}

func scaffold(opts initOptions, stdout io.Writer) error {
	templates, err := loadTemplates()
	if err != nil {
		return err
	}
	tpl, ok := templates[opts.template]
	if !ok {
		known := make([]string, 0, len(templates))
		for name := range templates {
			known = append(known, name)
		}
		return fmt.Errorf("unknown template %q (available: %s)", opts.template, strings.Join(known, ", "))
	}
	if problems := tpl.Validate(); len(problems) > 0 {
		return fmt.Errorf("template %q failed validation: %s", opts.template, strings.Join(problems, "; "))
	}

	secret := func() (string, error) {
		buf := make([]byte, 32)
		if _, err := rand.Read(buf); err != nil {
			return "", fmt.Errorf("generate secret: %w", err)
		}
		return hex.EncodeToString(buf), nil
	}
	jwtSecret, err := secret()
	if err != nil {
		return err
	}
	delegationSecret, err := secret()
	if err != nil {
		return err
	}
	webhookSecret, err := secret()
	if err != nil {
		return err
	}

	if err := os.MkdirAll(opts.dir, 0o700); err != nil {
		return fmt.Errorf("create %s: %w", opts.dir, err)
	}

	keyPair, err := generateRSAKeyPair()
	if err != nil {
		return err
	}
	privPath := filepath.Join(opts.dir, "delegation-rs256.pem")
	// The FILE env var must point at a path the runtime can read — the
	// absolute path is used so `groundwork doctor` works from anywhere.
	absPriv, err := filepath.Abs(privPath)
	if err != nil {
		return fmt.Errorf("resolve key path: %w", err)
	}

	policy, err := tpl.MarshalPolicy()
	if err != nil {
		return fmt.Errorf("render policy: %w", err)
	}

	files := map[string]string{
		filepath.Join(opts.dir, "groundwork.env"):           fmt.Sprintf(envTemplate, jwtSecret, filepath.ToSlash(absPriv), delegationSecret, webhookSecret),
		filepath.Join(opts.dir, "policy.json"):              string(policy) + "\n",
		filepath.Join(opts.dir, "README.md"):                renderReadme(opts.template, tpl.Description),
		filepath.Join(opts.dir, "delegation-rs256.pem"):     keyPair.private,
		filepath.Join(opts.dir, "delegation-rs256.pem.pub"): keyPair.public,
	}
	for path, content := range files {
		if err := writeIfAbsent(path, content, opts.force); err != nil {
			return err
		}
	}
	if !opts.force {
		if err := os.Chmod(privPath, 0o600); err != nil {
			return fmt.Errorf("chmod key pair: %w", err)
		}
	}

	fmt.Fprintf(stdout, "scaffolded deployment in %s\n", opts.dir)
	fmt.Fprintf(stdout, "  groundwork.env           runtime configuration with generated secrets\n")
	fmt.Fprintf(stdout, "  delegation-rs256.pem     RSA-2048 delegation signing key (RS256)\n")
	fmt.Fprintf(stdout, "  policy.json              starter policy (template %q, validated)\n", opts.template)
	fmt.Fprintf(stdout, "\nnext steps:\n")
	fmt.Fprintf(stdout, "  1. edit %s: set DATABASE_URL, SPICEDB_ENDPOINT, GROUNDWORK_ENV=production, GROUNDWORK_DEPLOYMENT_REGION\n", filepath.Join(opts.dir, "groundwork.env"))
	fmt.Fprintf(stdout, "  2. groundwork doctor --env-file %s\n", filepath.Join(opts.dir, "groundwork.env"))
	fmt.Fprintf(stdout, "  3. register the agent and apply policy.json via the governance API (POST /v1/agents, /v1/governance/tools, /v1/governance/grants, /v1/governance/budgets)\n")
	return nil
}

func writeIfAbsent(path, content string, force bool) error {
	if _, err := os.Stat(path); err == nil && !force {
		return fmt.Errorf("%s already exists (use --force to overwrite)", path)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func generateRSAKeyPair() (struct{ private, public string }, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return struct{ private, public string }{}, fmt.Errorf("generate RSA key: %w", err)
	}
	privPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	pubDER, err := x509.MarshalPKIXPublicKey(&key.PublicKey)
	if err != nil {
		return struct{ private, public string }{}, fmt.Errorf("marshal public key: %w", err)
	}
	pubPEM := pem.EncodeToMemory(&pem.Block{Type: "PUBLIC KEY", Bytes: pubDER})
	return struct{ private, public string }{string(privPEM), string(pubPEM)}, nil
}

func renderReadme(template, description string) string {
	return fmt.Sprintf(`# Groundwork deployment

Scaffolded by `+"`groundwork init --template %s`"+` — %s

Files:

- groundwork.env — runtime configuration (secrets: keep out of VCS).
- delegation-rs256.pem / .pub — RSA-2048 delegation signing key pair.
- policy.json — validated starter governance policy.

Next steps:

1. Edit groundwork.env: DATABASE_URL, SPICEDB_ENDPOINT, GROUNDWORK_ENV,
   GROUNDWORK_DEPLOYMENT_REGION, GROUNDWORK_TENANT_REGIONS.
2. Run the doctor: groundwork doctor --env-file groundwork.env
3. Start the runtime and register agents/tools/grants from policy.json.

See docs/KT.md and docs/production-scale-roadmap.md in the repository.
`, template, description)
}
